"""
Use case 16 - A chatbot that makes ZERO LLM calls.

No model writes a word. Jev picks the best video, then the best chapter inside
it, from lists you already have. The bot physically cannot hallucinate an
answer because it can only point at content that exists.

Run:  python3 chat.py
"""
import json, sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from _shared.jev_client import Jev, choice, noul      # noqa: E402

HERE = Path(__file__).parent
ANSWERABLE_AT = 0.5

QUESTIONS_SAMPLE = [
    ("how do I stop my bot inventing a refund policy", "S10a Why RAG"),
    ("my answers get cut in half between chunks", "S10b Chunking"),
    ("searching for an error code returns nothing", "S10d Hybrid search"),
    ("how do I prove a prompt change made things better", "S10e Evaluation"),
    ("I need the graph to pause for a human approval", "S11b Human in the loop"),
    ("what is the difference between LoRA and QLoRA", "S15 Fine tuning"),
    ("how do I log in with Cognito", "S14 AgentCore"),
    ("what is the weather in Dubai tomorrow", None),      # outside the library
]


def answer(jev: Jev, library: list[dict], question: str):
    videos = {v["video"]: ", ".join(c["title"] for c in v["chapters"])
              for v in library}
    videos["none"] = "No video in this library covers that question."

    first = jev.ask({"question": question},
                    {"video": choice("Which video best answers `question`?", videos)})["video"]
    if first["choice"] == "none" or first["confidence"] < ANSWERABLE_AT:
        return None, None, first["confidence"]

    vid = next(v for v in library if v["video"] == first["choice"])
    chapters = {str(i): c["title"] for i, c in enumerate(vid["chapters"])}
    second = jev.ask({"question": question, "video": vid["video"]},
                     {"chapter": choice("Which chapter answers `question`?", chapters)})["chapter"]
    ch = vid["chapters"][int(second["choice"])]
    return vid["video"], ch, first["confidence"]


def main() -> None:
    library = json.loads((HERE / "data" / "library.json").read_text())
    jev = Jev()
    hits = 0

    for q, expected in QUESTIONS_SAMPLE:
        video, chapter, conf = answer(jev, library, q)
        print(f'\nQ: "{q}"')
        if video is None:
            print(f"   -> Not covered in the library (confidence {conf:.2f}). "
                  f"No answer invented.")
            ok = expected is None
        else:
            mm = f"{chapter['start']//60}:{chapter['start']%60:02d}"
            print(f"   -> {video}  @ {mm}  \"{chapter['title']}\"  (confidence {conf:.2f})")
            ok = expected == video
        hits += ok
        if not ok:
            print(f"      expected: {expected}")

    print(f"\n{hits}/{len(QUESTIONS_SAMPLE)} routed correctly")
    print(jev.report("zero-LLM chatbot"))
    print("\nTokens generated by a language model writing prose: 0")
    print("Every answer is a pointer to content that already exists, so the bot "
          "cannot state a fact that is not in the library.")
    assert hits >= len(QUESTIONS_SAMPLE) - 1, f"too many misroutes: {hits}"


if __name__ == "__main__":
    main()
